name: pop_store
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  localization: ^2.1.0
  google_fonts: ^2.3.1
  get: ^4.6.1
  flutter_screenutil: ^5.3.1
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  google_sign_in: ^5.2.4
  flutter_facebook_auth: ^4.1.1
  get_storage: ^2.0.3
  http: ^0.13.4
  badges: ^2.0.2
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.0.0
  flutter_rating_bar: ^4.0.0
  readmore: ^2.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
